/**
 * Reel-level model constraints — resolves the full set of models a reel will
 * run on into the constraint lists the orchestrator LLM and the UI both read
 * (src/skills/model-prompt/constraints.ts).
 *
 * WHY A SEPARATE MODULE FROM ./routing.ts: routing answers "which model runs
 * for THIS scene", which needs a scene. This answers "which models is this reel
 * committed to", which the setup form has to answer before a single scene
 * exists — and which scene-brain needs precisely because it is the thing that
 * invents the scenes.
 *
 * WHY IT TAKES A PLAIN SELECTION, NOT A ReelConfigRow: the reel-setup page has
 * to re-resolve on every dropdown change, against form state that has not been
 * saved yet. Accepting the narrow shape below lets the same function serve the
 * unsaved form and the persisted row, so the panel the user reads while
 * choosing a model is generated by the same code as the block scene-brain is
 * given afterwards — they cannot disagree.
 *
 * Kept free of adapter/SDK imports for the same reason src/lib/brollModels.ts
 * is: it is imported by client components.
 */
import {
  constraintsFor,
  renderConstraintsForPrompt,
  type ModelConstraints,
  type ReelModelContext,
} from "@/src/skills/model-prompt/constraints";
import { veoRenderPlan } from "@/src/skills/model-prompt/veo";
import { heygenDurationCheck } from "@/src/skills/model-prompt/heygen";
import type { VeoVariant } from "@/src/lib/db/enums";

/**
 * The subset of a reel's setup that determines its model constraints. Mirrors
 * the `reel_config` columns of the same name; `has_product_references` is
 * derived from `product_reference_paths`.
 */
export interface ReelModelSelection {
  broll_provider: string | null;
  veo_variant: string | null;
  avatar_enabled: boolean;
  image_provider: string | null;
  music_provider: string | null;
  aspect_ratio: string;
  resolution: string;
  has_product_references: boolean;
}

/**
 * `uses_end_frames` defaults to undefined = "not known here", which resolves to
 * the conditional phrasing ("a continuous boundary would force 8s") rather than
 * the definite one. Pass `true` only from a caller that knows a last frame is
 * actually being supplied — a specific scene sitting on a continuous boundary.
 */
export interface ConstraintResolveOpts {
  uses_end_frames?: boolean;
}

function contextFor(selection: ReelModelSelection, opts: ConstraintResolveOpts = {}): ReelModelContext {
  return {
    aspect_ratio: selection.aspect_ratio,
    resolution: selection.resolution,
    uses_end_frames: opts.uses_end_frames ?? false,
    uses_reference_images: selection.has_product_references,
  };
}

/**
 * Every model this reel is committed to, in pipeline order (b-roll, avatar,
 * image, music), skipping the ones it does not use. Ordering matters: the
 * b-roll model owns the duration rules, which is the fact scene-brain most
 * needs to read first.
 */
export function reelConstraintSets(
  selection: ReelModelSelection,
  opts: ConstraintResolveOpts = {}
): ModelConstraints[] {
  const ctx = contextFor(selection, opts);
  const sets = [
    selection.broll_provider ? constraintsFor(selection.broll_provider, selection.veo_variant, ctx) : null,
    selection.avatar_enabled ? constraintsFor("heygen", null, ctx) : null,
    selection.image_provider ? constraintsFor(selection.image_provider, null, ctx) : null,
    selection.music_provider ? constraintsFor(selection.music_provider, null, ctx) : null,
  ];
  return sets.filter((s): s is ModelConstraints => s !== null);
}

/**
 * The constraint sets scene-brain is given: b-roll and avatar only.
 *
 * Deliberately narrower than `reelConstraintSets` — scene-brain allocates
 * durations and transitions, so the image and music models' rules are noise it
 * would have to read past on every call. Those two are injected at the stage
 * that actually writes their prompts.
 */
export function sceneBrainConstraintSets(selection: ReelModelSelection): ModelConstraints[] {
  const ctx = contextFor(selection);
  return [
    selection.broll_provider ? constraintsFor(selection.broll_provider, selection.veo_variant, ctx) : null,
    selection.avatar_enabled ? constraintsFor("heygen", null, ctx) : null,
  ].filter((s): s is ModelConstraints => s !== null);
}

/** Convenience for the stages: resolve and render in one step. Empty string when nothing is selected. */
export function renderReelConstraints(sets: ModelConstraints[]): string {
  return renderConstraintsForPrompt(sets);
}

/**
 * The `ReelModelContext` a per-call prompt skill passes alongside its
 * `TargetModel`. Takes the persisted row directly, since every call site that
 * needs one has already loaded it.
 *
 * Pass `uses_end_frames` when the caller knows this particular scene or slot
 * sits on a continuous boundary — it upgrades the constraint wording from the
 * conditional rule to a statement about this clip.
 */
export function reelModelContext(
  config: Parameters<typeof selectionFromReelConfig>[0],
  opts: ConstraintResolveOpts = {}
): ReelModelContext {
  return contextFor(selectionFromReelConfig(config), opts);
}

/**
 * What the scene editor tells the user about one row: whether the seconds they
 * typed are what will actually be rendered.
 *
 * `blocking` means the clip call is rejected outright and the scene never
 * generates; `forced` means it generates, but at a different length than the
 * number in the box. Returning `null` means the typed value is exactly what
 * runs — the common case, and the one that gets no badge at all, so the badges
 * that do appear carry signal.
 */
export interface SceneRenderNote {
  severity: "blocking" | "forced";
  message: string;
}

/** The scene fields that decide how it renders. Structural, so unsaved editor rows fit too. */
export interface SceneRenderInput {
  type: "avatar" | "broll";
  seconds: number;
  /** Effective, not merely intended: pass false when the model cannot honour a continuous boundary. */
  uses_end_frame: boolean;
}

export function sceneRenderNote(scene: SceneRenderInput, selection: ReelModelSelection): SceneRenderNote | null {
  if (scene.type === "avatar") {
    const check = heygenDurationCheck(scene.seconds);
    return check.ok
      ? null
      : {
          severity: "blocking",
          message: `Avatar scenes must be ${check.min}–${check.max}s — this one is rejected before generation and will block the clip.`,
        };
  }

  // Only the Veo-family adapter is selectable today; other b-roll providers
  // have no verified duration rules to report (see higgsfieldConstraints), so
  // stay silent rather than guess.
  if (selection.broll_provider !== "veo") return null;

  const ctx = contextFor(selection, { uses_end_frames: scene.uses_end_frame });
  const plan = veoRenderPlan((selection.veo_variant ?? "fast") as VeoVariant, ctx, scene.seconds);

  switch (plan.reason) {
    case "as_requested":
      return null;
    case "model_chooses":
      return {
        severity: "forced",
        message: `This model has no duration control — it returns 3–10s of its own choosing, trimmed to ${scene.seconds}s.`,
      };
    case "forced_by_resolution":
      if (plan.generated_s === scene.seconds) return null;
      // No "switch to a hard cut" hint here even when this scene also has a
      // continuous boundary: the resolution forces the full length on its own,
      // so changing the transition would not shorten the render by a second.
      return {
        severity: "forced",
        message: `Renders ${plan.generated_s}s (${selection.resolution} is only produced at full length), billed at ${plan.generated_s}s, trimmed to ${scene.seconds}s.`,
      };
    case "forced_by_end_frame":
      if (plan.generated_s === scene.seconds) return null;
      return {
        severity: "forced",
        message: `Renders ${plan.generated_s}s (a continuous boundary puts this model in interpolation mode), billed at ${plan.generated_s}s, trimmed to ${scene.seconds}s. Switch to a hard cut to render at ${scene.seconds}s.`,
      };
    case "rounded_up":
      return {
        severity: "forced",
        message: `Renders ${plan.generated_s}s (the nearest length this model produces), billed at ${plan.generated_s}s, trimmed to ${scene.seconds}s.`,
      };
  }
}

/**
 * Builds the selection from a persisted `reel_config` row. Typed structurally
 * rather than against `ReelConfigRow` so this module stays importable from a
 * client component without dragging the whole db types graph in.
 */
export function selectionFromReelConfig(config: {
  broll_provider: string | null;
  veo_variant: string | null;
  avatar_enabled: boolean;
  image_provider: string | null;
  music_provider: string | null;
  aspect_ratio: string;
  resolution: string;
  product_reference_paths?: string[] | null;
}): ReelModelSelection {
  return {
    broll_provider: config.broll_provider,
    veo_variant: config.veo_variant,
    avatar_enabled: config.avatar_enabled,
    image_provider: config.image_provider,
    music_provider: config.music_provider,
    aspect_ratio: config.aspect_ratio,
    resolution: config.resolution,
    has_product_references: (config.product_reference_paths?.length ?? 0) > 0,
  };
}
